apiVersion: v1
kind: Service
metadata:
  name: ccbd-micro-service-2
spec:
  selector:
    app: ccbd-micro-service-2
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
  type: LoadBalancer
