apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccbd-app2-deployment-micro-service-2
  labels:
    app: ccbd-micro-service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccbd-micro-service-2
  template:
    metadata:
      labels:
        app: ccbd-micro-service-2
    spec:
      containers:
      - name: ccbd-micro-service-2
        image: veera491/ccbd-micro-services:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:veera491@postgres-service:5432/ccbd_db"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
